id = "liquid"
name = "Liquid"
version = "0.12.0"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/redasalmi/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/redasalmi/tree-sitter-liquid"
commit = "9c1a5e1f8647206eaeb4ddb0a19cfa9f51b7b918"

[language_servers.liquid]
name = "Shopify Theme Language Server"
languages = ["Liquid"]

[language_servers.liquid-embedded-javascript]
name = "Liquid Embedded Support"
languages = ["Liquid"]
