id = "liquid"
name = "Liquid"
version = "1.0.2"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/redasalmi/zed-shopify-liquid"
snippets = ["./snippets/liquid.json"]

[grammars.liquid]
repository = "https://github.com/redasalmi/tree-sitter-liquid"
commit = "0e228e6d080f1fc7b0e6a661479004c16c8d2514"

[language_servers.liquid]
name = "Shopify Theme Language Server"
languages = ["Liquid", "JSON"]

[language_servers.liquid.language_ids]
Liquid = "liquid"
JSON = "json"

[language_servers.liquid-embedded-javascript]
name = "Liquid Embedded Support"
languages = ["Liquid"]

[language_servers.liquid-embedded-javascript.language_ids]
Liquid = "liquid"
