id = "liquid"
name = "Liquid"
version = "0.20.0"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
description = "Shopify Liquid support"
repository = "https://github.com/redasalmi/zed-shopify-liquid"

[grammars.liquid]
repository = "https://github.com/redasalmi/tree-sitter-liquid"
commit = "e229daeca9b64337451e02db52b1b92da77961b2"

[language_servers.liquid]
name = "Shopify Theme Language Server"
languages = ["Liquid"]

[language_servers.liquid-embedded-javascript]
name = "Liquid Embedded Support"
languages = ["Liquid"]
