name = "Liquid"
grammar = "liquid"
path_suffixes = ["liquid"]
autoclose_before = "%- \t\r\n)}]>,:;"
word_characters = ["-", "?"]
tab_size = 2
prettier_parser_name = "liquid-html"
brackets = [
    { start = "{{", end = "}}", close = true, newline = false },
    { start = "{{-", end = "-}}", close = true, newline = false },
    { start = "{%", end = "%}", close = true, newline = false },
    { start = "{%-", end = "-%}", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
]
block_comment = { start = "{% comment %}", prefix = "", end = "{% endcomment %}", tab_size = 2 }
documentation = { start = "{% doc %}", end = "{% enddoc %}", prefix = " ", tab_size = 1 }
completion_query_characters = ["-"]
